create database DDL;
go
use DDL;
GO
1. create table TRG_DEPT (ID int primary key, NAME VARCHAR(25));
SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TRG_DEPT';


2. CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(50)
);
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (1, 'ICE'), (2, 'EEE'), (3, 'ECE');
SELECT * FROM DEPARTMENTS


3. CREATE TABLE TRG_EMP (
    ID INT,  
    LAST_NAME VARCHAR(25), 
    FIRST_NAME VARCHAR(25), 
    DEPT_ID INT  
);


4. ALTER TABLE TRG_EMP  
ALTER COLUMN LAST_NAME VARCHAR(50);


5. CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    SALARY DECIMAL(10,2),
    DEPARTMENT_ID INT
);
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID)
VALUES 
    (1,'ABHINAYA','MOHAN', 50000.00, 1),
    (2,'MOHAN','KARI', 60000.00, 2),
    (3,'NAVEENA','GOWDAR', 65000.00, 1);
SELECT EMPLOYEE_ID AS ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID AS DEPT_ID  
INTO TRG_EMPLOYEES  
FROM EMPLOYEES;
SELECT * FROM TRG_EMPLOYEES;

6. DROP TABLE TRG_EMP;

7. ALTER TABLE TRG_EMPLOYEES RENAME TO TRG_EMP;

8. ALTER TABLE TRG_EMP DROP COLUMN FIRST_NAME;

