CREATE DATABASE DML;
GO
USE DML;
GO

1. CREATE TABLE MY_EMPLOYEE (
    ID         INT,
    LAST_NAME  VARCHAR(25),
    FIRST_NAME VARCHAR(25),
    USERID     VARCHAR(8),
    SALARY     INT,
    CONSTRAINT PK_EMPLOYEE_ID PRIMARY KEY (ID)
);

2. INSERT INTO MY_EMPLOYEE
VALUES (1, 'ABHI', 'MOHAN', 'abhinaya', 50000);

3. INSERT INTO MY_EMPLOYEE (ID, LAST_NAME, FIRST_NAME, USERID, SALARY)
VALUES (2, 'NAVEENA', 'MOHAN', 'naveen', 60000), (3, 'MOHAN', 'KARI', 'kari', 70000);

4. SELECT * FROM MY_EMPLOYEE;

5. DECLARE @ID INT, @LAST_NAME VARCHAR(25), @FIRST_NAME VARCHAR(25), @SALARY DECIMAL(9,2), @USERID VARCHAR(8);
SET @ID = 3;
SET @LAST_NAME = 'SARASWATHY';
SET @FIRST_NAME = 'MOHAN';
SET @SALARY = 950;
SET @USERID = UPPER(LEFT(@FIRST_NAME, 1) + LEFT(@LAST_NAME, 7));

6. UPDATE MY_EMPLOYEE
SET LAST_NAME = 'harish'
WHERE ID = 2;

7. UPDATE MY_EMPLOYEE
SET SALARY = 65000
WHERE SALARY < 68000;
SELECT * FROM MY_EMPLOYEE;


8. DELETE FROM MY_EMPLOYEE
WHERE FIRST_NAME = 'MOHAN' AND LAST_NAME = 'harish';


9. TRUNCATE TABLE MY_EMPLOYEE;
